use_frameworks!

target 'SoundCloudy' do
  pod 'SnapKit', '~> 0.1'
  pod 'RealmSwift', '~> 0.9'
  pod 'KeychainSwift', '~> 3.0'
  pod 'RxSwift',    '~> 2.1'
  pod 'RxCocoa',    '~> 2.1'
end

target 'SoundCloudyTests' do
  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 3.1'
  pod 'RxBlocking', '~> 2.0'
  pod 'RxTests',    '~> 2.0'
end

